name: Mise Ã  jour automatique des confÃ©rences

on:
  schedule:
    - cron: '0 0 * * *' # Lance le bot tous les jours Ã  minuit
  workflow_dispatch: # Permet de lancer manuellement depuis l'onglet Actions

permissions:
  contents: write # ðŸ‘ˆ C'est cette ligne magique qui manquait !

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Installation de Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Lancement du Bot de recherche
      run: python update_conferences.py

    - name: Sauvegarde des changements
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action Bot"
        git add app.js
        git commit -m "Mise Ã  jour automatique des confÃ©rences" || echo "Aucune nouvelle confÃ©rence."
        git push
